/**
 * Client-side export utilities for compliance reports.
 *
 * All exports include:
 * - Report name & generated timestamp
 * - Sample-data disclaimer
 * - Governance disclaimer
 * - Applied filters
 * - Data rows
 *
 * Phase 2.8: Enhanced with snapshot ID, checksum, and metadata envelope fields.
 * In database mode, exports should first create a server-side snapshot via
 * /api/reports/export, then include the returned snapshotId/checksum.
 *
 * No server-side generation. No external dependencies.
 */

// ── Report Metadata ─────────────────────────────────────────────

export interface ReportMeta {
  reportId: string;
  reportName: string;
  reportType: string;
  generatedAt: string;
  generatedBy: string;
  dataScope: string;
  filtersApplied: Record<string, string>;
  sourceDatasets: string[];
  includesSampleData: boolean;
  governanceDisclaimer: string;
  sampleDataDisclaimer: string;
  recordCount: number;
  // Phase 2.8: Snapshot traceability
  snapshotId?: string;
  checksum?: string;
  checksumAlgorithm?: string;
  exportFormat?: string;
}

export function buildReportMeta(
  partial: Pick<ReportMeta, 'reportId' | 'reportName' | 'reportType' | 'dataScope' | 'sourceDatasets' | 'recordCount'> & {
    filtersApplied?: Record<string, string>;
    snapshotId?: string;
    checksum?: string;
    exportFormat?: string;
  }
): ReportMeta {
  return {
    ...partial,
    generatedAt: new Date().toISOString(),
    generatedBy: 'Demo User',
    filtersApplied: partial.filtersApplied ?? {},
    includesSampleData: true,
    governanceDisclaimer:
      'This report is generated from sample/demonstration data. Not validated for regulatory decisions. Not legal advice. Not a validated GxP system.',
    sampleDataDisclaimer:
      'This export contains demonstration data only. Not validated for regulatory, legal, or compliance decisions.',
    snapshotId: partial.snapshotId,
    checksum: partial.checksum,
    checksumAlgorithm: partial.checksum ? 'sha256' : undefined,
    exportFormat: partial.exportFormat,
  };
}

// ── CSV Export ───────────────────────────────────────────────────

function escapeCSV(value: unknown): string {
  if (value === null || value === undefined) return '';
  const str = String(value);
  if (str.includes(',') || str.includes('"') || str.includes('\n') || str.includes('\r')) {
    return '"' + str.replace(/"/g, '""') + '"';
  }
  return str;
}

export function exportToCSV(
  meta: ReportMeta,
  columns: { key: string; label: string }[],
  rows: Record<string, unknown>[]
): void {
  const lines: string[] = [];

  // Metadata header
  lines.push(`# Report: ${meta.reportName}`);
  lines.push(`# Type: ${meta.reportType}`);
  lines.push(`# Generated: ${meta.generatedAt}`);
  lines.push(`# Generated By: ${meta.generatedBy}`);
  lines.push(`# Scope: ${meta.dataScope}`);
  lines.push(`# Records: ${meta.recordCount}`);
  lines.push(`# Sources: ${meta.sourceDatasets.join('; ')}`);
  lines.push(`# Export Format: CSV`);

  const filterEntries = Object.entries(meta.filtersApplied);
  if (filterEntries.length > 0) {
    lines.push(`# Filters: ${filterEntries.map(([k, v]) => `${k}=${v}`).join('; ')}`);
  }

  // Phase 2.8: Snapshot traceability
  if (meta.snapshotId) {
    lines.push(`# Snapshot ID: ${meta.snapshotId}`);
  }
  if (meta.checksum) {
    lines.push(`# Checksum (SHA-256): ${meta.checksum}`);
  }

  lines.push(`# DISCLAIMER: ${meta.governanceDisclaimer}`);
  lines.push(`# SAMPLE DATA: ${meta.sampleDataDisclaimer}`);
  lines.push('');

  // Column headers
  lines.push(columns.map((c) => escapeCSV(c.label)).join(','));

  // Data rows
  for (const row of rows) {
    lines.push(columns.map((c) => escapeCSV(row[c.key])).join(','));
  }

  const blob = new Blob([lines.join('\r\n')], { type: 'text/csv;charset=utf-8;' });
  downloadBlob(blob, `${meta.reportId}_${formatFileDate(meta.generatedAt)}.csv`);
}

// ── JSON Export ──────────────────────────────────────────────────

export function exportToJSON(
  meta: ReportMeta,
  columns: { key: string; label: string }[],
  rows: Record<string, unknown>[]
): void {
  const envelope = {
    metadata: {
      ...meta,
      exportFormat: 'json',
    },
    schema: columns.map((c) => ({ field: c.key, label: c.label })),
    data: rows,
  };

  const blob = new Blob([JSON.stringify(envelope, null, 2)], { type: 'application/json;charset=utf-8;' });
  downloadBlob(blob, `${meta.reportId}_${formatFileDate(meta.generatedAt)}.json`);
}

// ── Print ────────────────────────────────────────────────────────

export function triggerPrint(): void {
  window.print();
}

// ── Helpers ──────────────────────────────────────────────────────

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function formatFileDate(iso: string): string {
  return iso.slice(0, 10).replace(/-/g, '');
}
