/**
 * ListItem — From the "Lists" sheet (controlled vocabulary).
 * 7 fields. Used to populate filter dropdowns and validate values.
 */
export interface ListItem {
  listId: string;                         // LIST-SEVERITY_PRIORITY-001 …
  listCategory: string;                   // e.g., "Severity / Priority"
  listValue: string;                      // The raw value
  displayLabel: string;                   // Human-readable label
  definition: string | null;
  sortOrder: number;
  active: boolean;                        // Parsed from "TRUE"/"FALSE"
}

/**
 * DecisionNode — From the "Applicability Decision Tree" sheet.
 */
export interface DecisionNode {
  decisionId: string;                     // DEC-001 …
  decisionArea: string | null;
  question: string | null;
  ifYes: string | null;
  ifNo: string | null;
  likelyOwner: string | null;
  matrixUse: string | null;
  appUse: string | null;
}

/**
 * RoadmapItem — From the "Implementation Roadmap" sheet.
 */
export interface RoadmapItem {
  roadmapId: string;                      // ROAD-001 …
  priority: string | null;
  workstream: string | null;
  enhancement: string | null;
  whyItMatters: string | null;
  owner: string | null;
  suggestedTiming: string | null;
  deliverable: string | null;
  successMeasure: string | null;
  linkedGapRiskTheme: string | null;
  status: string | null;
}

/**
 * VerificationSource — From the "Verification Sources" sheet.
 */
export interface VerificationSource {
  verificationSourceId: string;           // VSRC-001 …
  sourceName: string | null;
  type: string | null;
  whyUsed: string | null;
  url: string | null;
  reviewNote: string | null;
  linkedSourceId: string | null;
}

/**
 * ImportMetadata — Generated by the import script.
 */
export interface ImportMetadata {
  workbookVersion: string;
  revisionDate: string;
  importedAt: string;
  sourceFile: string;
  rowCounts: Record<string, number>;
  warnings: string[];
}
