/**
 * Stable Reference ID Generator — Creates unique, human-readable IDs for new records.
 *
 * Format: {PREFIX}-{timestamp36}-{random4}
 * Example: RU-lkj3f8-a9z2
 *
 * These IDs are used as stableReferenceId in draft/staging tables.
 * They are NOT database UUIDs — those are generated by PostgreSQL.
 */

/** Generate a new regulatory update stable reference ID */
export function generateRegulatoryUpdateId(): string {
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 6);
  return `RU-${ts}-${rand}`;
}

/** Generate a new draft change stable reference ID */
export function generateDraftChangeId(): string {
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 6);
  return `DRC-${ts}-${rand}`;
}

/** Generate a new approval review stable reference ID */
export function generateApprovalReviewId(): string {
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 6);
  return `AR-${ts}-${rand}`;
}

/** Generate a new publication event stable reference ID */
export function generatePublicationEventId(): string {
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 6);
  return `PE-${ts}-${rand}`;
}

/** Generate a new version record ID */
export function generateVersionId(): string {
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 6);
  return `VER-${ts}-${rand}`;
}

/** Generate a new reference record stable reference ID */
export function generateReferenceRecordId(): string {
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 6);
  return `REF-${ts}-${rand}`;
}

/** Generate a new source record stable reference ID */
export function generateSourceRecordId(): string {
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 6);
  return `SRC-${ts}-${rand}`;
}

/** Generate a new report snapshot stable reference ID */
export function generateSnapshotId(): string {
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 6);
  return `SNAP-${ts}-${rand}`;
}

/** Generate a new source file metadata stable reference ID */
export function generateSourceFileId(): string {
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 6);
  return `SF-${ts}-${rand}`;
}

/** Generate a new source intake request stable reference ID */
export function generateSourceIntakeRequestId(): string {
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 6);
  return `SIR-${ts}-${rand}`;
}

/** Generate a new source intake checklist item ID */
export function generateIntakeChecklistItemId(): string {
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 6);
  return `SIC-${ts}-${rand}`;
}

/** Generate a new AI extraction suggestion stable reference ID */
export function generateAiSuggestionId(): string {
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 6);
  return `AIS-${ts}-${rand}`;
}

/** Generate a new AI prompt version stable reference ID */
export function generateAiPromptVersionId(): string {
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 6);
  return `APR-${ts}-${rand}`;
}

/** Generate a new draft validation review stable reference ID (Phase 3.10) */
export function generateDraftValidationReviewId(): string {
  const ts = Date.now().toString(36);
  const rand = Math.random().toString(36).slice(2, 6);
  return `DVR-${ts}-${rand}`;
}
